# Generated by Django 5.1.15 on 2026-04-18 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_booking_completion_confirmations'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='compensation_type',
            field=models.CharField(choices=[('money', 'Money'), ('service', 'Service swap')], default='money', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='offered_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_in_bookings', to='marketplace.service'),
        ),
    ]
